import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { files, repoName, githubToken } = await req.json();

    if (!githubToken || !repoName || !files) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const headers = {
      Authorization: `token ${githubToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    };

    // 1. Get the authenticated user's username
    const userRes = await fetch("https://api.github.com/user", { headers });
    if (!userRes.ok) throw new Error("Invalid GitHub Token");
    const userData = await userRes.json();
    const owner = userData.login;

    // 2. Create the new repository (Auto-initialized with a README)
    const repoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: repoName,
        description: "Generated by Spark AI",
        private: false,
        auto_init: true, // Creates the initial commit so we have a branch to push to
      }),
    });
    
    if (!repoRes.ok) {
      const errorData = await repoRes.json();
      throw new Error(`Failed to create repo: ${errorData.message}`);
    }
    const repoData = await repoRes.json();
    const defaultBranch = repoData.default_branch; // usually 'main'

    // 3. Get the SHA of the latest commit on the default branch
    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/${defaultBranch}`, { headers });
    const refData = await refRes.json();
    const commitSha = refData.object.sha;

    // 4. Get the tree SHA of that commit
    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits/${commitSha}`, { headers });
    const commitData = await commitRes.json();
    const baseTreeSha = commitData.tree.sha;

    // 5. Create a new Tree containing all our AI generated files
    const treeData = Object.entries(files).map(([path, content]) => ({
      path: path.replace(/^\//, ""), // Remove leading slash
      mode: "100644", // standard file mode
      type: "blob",
      content: content as string,
    }));

    const newTreeRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/trees`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: treeData,
      }),
    });
    const newTreeData = await newTreeRes.json();

    // 6. Create a new Commit pointing to the new Tree
    const newCommitRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        message: "Initial commit from Spark AI 🚀",
        tree: newTreeData.sha,
        parents: [commitSha],
      }),
    });
    const newCommitData = await newCommitRes.json();

    // 7. Update the branch reference to point to our new commit
    await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/${defaultBranch}`, {
      method: "PATCH",
      headers,
      body: JSON.stringify({
        sha: newCommitData.sha,
      }),
    });

    return NextResponse.json({ url: repoData.html_url });
    
  // 🚀 FIXED: Used 'unknown' and checked if it's an instance of Error
  } catch (error: unknown) {
    console.error("GitHub Export Error:", error);
    const errorMessage = error instanceof Error ? error.message : "Failed to export to GitHub";
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}